### PR TITLE
[PR] Added support for Audio-Profiles & Variable bitrate (audio)

### PR DESCRIPTION
**Pull request by Mirabis**
Adds support for High-Efficiency AAC (v1 & v2) and possibly other profiles one may want to specify.

Also small fix for having 'mov_text' specified and encoding set to 'utf-8' causing errors. Perhaps that fix could have been done prettier.

Additionally, adds support for Variable Bitrates on codecs that supported it.

Ran tests on Windows 10 with nvenc_h264, h264 and h264_qsv aac & libfdk_aac.

ref: https://trac.ffmpeg.org/wiki/Encode/AAC

### CODE REVIEW

**Comment by Mirabis** [comment]
Gonna re-submit PR.

**Comment by Mirabis** [comment]
Was there any specific reason why this Pull request was ignored? If so, please let me know - then I won't spend time this holiday to fix the conflichts.

**Comment by VXsz** [comment]
This should be merged

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/commit/ef4bdbd7142bbbe113b0e17aa1d4816e65ea5cf5

This close this out

**Pull request closed without merging**
