### PR TITLE
manual.py - Adds in a check for output files and skips processing if they exists.

### PR DESCRIPTION
**Pull request by KurtisVargas**
This is the full debugged version of a patch that I left in a comment a few weeks ago.

This patch adds a command line option to manual.py that will check if the output file already exists before processing the input file.  Trivial change but this enables two key features:
1) Manual.py can run multiple times on the same collection of input files to mass update an entire collection.  Great for mass updates or mass conversions.
2) Networked machines can work simultaneously on the same collection so long as the output-folder is the same.

### CODE REVIEW

**Comment by HazCod** [comment]
A more correct approach would be ffprobe looking if the output file has the required codec/audio stream(s), no?

**Comment by mdhiggins** [comment]
Yeah I think HazCod's approach would be the more ideal way to handle this. Its something that I may look to add in future versions, but not something too high on the to-do list at the moment.

**Comment by lowne** [comment]
@mdhiggins  *please* merge this. I've stashed-and-applied it for years now, since it's required by my workflow - and before this I *did* experience catastrophic data loss due to something upstream going haywire.

The probe approach, while laudable, is an orthogonal feature meant for not-necessarily-overlapping use cases (e.g. it would not have prevented *my* specific situation), and it also has the non-trivial drawback of *not having an implementation yet*. This patch has existed for over 3 years, is straightforward, tested, and - let me repeat - **prevents data loss**.

**Comment by stevemk14ebr** [comment]
here's a better way to do this. It builds a whitelist as files are processed:

manual.py:
```
...at top as global...
processed = None
...later...

def checkAlreadyProcessed(inputfile):
    global processed
    serializedFile = os.path.join(sys.path[0], 'processed.json')

    if processed is None:
        try:
            with open(serializedFile, 'r') as infile:
                processed = set(json.load(infile))
        except:
            processed = set()

    if inputfile in processed:
        return True
    else:
        processed.add(inputfile)
        with open(serializedFile, 'w') as outfile:
            json.dump(list(processed), outfile)
        return False

...later...
def processFile(inputfile, tagdata, converter, info=None, relativePath=None):
    if checkAlreadyProcessed(inputfile):
        return
        
     # do rest of processing
...more stuff...
```

**Comment by mafhper** [comment]
Something like that would be really cool.

**Comment by mdhiggins** [comment]
Closing with #1516

**Pull request closed without merging**
