### PR TITLE
Handling of language codes

### PR DESCRIPTION
**Pull request by phtagn**
Hi,

I have a recurring problem with subtitles embedded in mkv files. Quite often, they are coded using alpha3b codes, e.g. using 'fre' when the alpha3 code is 'fra' for French.
The problem is:
- If I don't include 'fre' in the swl list, the subtitles do not get picked up 
- If I include 'fre' in the swl list, then the subtitles get picked up, but the mkvtomp4 script errors on line 555, because babelfish expects alpha3 codes, not alpha3b codes. (NB: this does not happen with audio, where I can include both codes).

I did some research, and the spec for mp4 is that yet another ISO standard should be used, namely alpha3t (ISO-639-2/T) (you can see it [here](http://standards.iso.org/ittf/PubliclyAvailableStandards/c041828_ISO_IEC_14496-12_2005(E).zip), in section 8.8)

I thought it was a good idea to set things up so that:
swl, awl, sdl, and adl  all use alpha3t code and then convert the subtitle.metadata['language'] and audio.metadata['language'], to alpha3t codes too, to make sure that equivalent things are compared. Otherwise, users would need to put all codes in autoProcess.ini to make sure that they include their language in the processed file, which also leads to unnecessary iterations in the various loops (checking once for 'fre', and once for 'fra' is inefficient).

French is not the only language with this problem, Chinese, Dutch, German and other languages have different alpha3b and alpha3 codes too.

Please, do tell me if you want me to amend the code. I am not a professional developer, so things may be inelegant, or there just might be a better way that I just don't know about. I'm happy to improve.

Thanks you and kind regards,

Jon

### CODE REVIEW

**Comment by danama** [comment]
I have tested this PR and it solves the issues on my side with french subs. Thanks @phtagn !

**Comment by Collisionc** [comment]
Minor thing that you may want to fix, this  breaks python3 compatibility when using manual.py.

In the languagecode.py file, you'll need to add a check for python 2, as basestring is dropped in python3. 

Something like this: 
```

import sys
IS_PY2 = sys.version_info[0] == 2


def validateLangCode(code):
    """
    :param code: alpha2, alpha3 or alpha3b code or list of codes
    :type code: list or string
    :return:  list or string containing valid alpha3 codes
    """
    lang = 'und'
    if code:
        if isinstance(code, list):
            lang = filter(lambda x: x != 'und', list(set(map(getAlpha3TCode, code))))
            lang = 'und' if lang == [] else lang
        elif IS_PY2:
            if isinstance(code, basestring):
                lang = getAlpha3TCode(code)
        else:
            if isinstance(code, bytes):
                lang = getAlpha3TCode(code)

    return lang

```

**Comment by phtagn** [comment]
Ok, thanks. I’ll fix this tonight.

**Comment by mdhiggins** [comment]
While this exact pull is dated this feature was implemented recently

**Pull request closed without merging**
