### PR TITLE
Check for field_order value

### PR DESCRIPTION
**Pull request by allenderj**
Check for field_order value of "unknown" and set to the value of the default of progressive. 

unknown is not a valid value and is returned on some avi's

### CODE REVIEW

**Comment by mdhiggins** [comment]
I'm wondering if a method more in line with how other parameters are filtered would be
```
    def parse_options(self, opt, stream=0):
        ...
        if 'field_order' in safe:
            if safe['field_order'] not in ['progressive', 'tt', 'bb', 'tb', 'bt']:
                del safe['field_order']
```

**Comment by mdhiggins** [comment]
I think ffmpeg defaults to progressive when the parameter isn't set anyway

**Comment by allenderj** [comment]
ffmpeg does default to progressive but some file when scanned before processing are returning field_order of unknown. I am thinking catch the unknown value and set back to the default.

2020-02-11 02:11:53 - mkvtomp4 - INFO - Reading video stream.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Video codec detected: mpeg4.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Pix Fmt: yuv420p.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Profile: Advanced Simple Profile.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Reading audio streams.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Audio detected for stream 1 - mp3 eng 2 channel.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Creating aac audio stream 0 from source stream 1.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Default audio stream set to eng aac 2 channel stream [prefer-more-channels: True].
2020-02-11 02:11:53 - mkvtomp4 - INFO - Reading subtitle streams.
2020-02-11 02:11:53 - mkvtomp4 - INFO - Output Data
2020-02-11 02:11:53 - mkvtomp4 - INFO - {
    "subtitle": {},
    "audio": {
        "0": {
            "channels": 2,
            "map": 1,
            "codec": "aac",
            "disposition": "+default",
            "language": "eng",
            "debug": "base.ios-audio",
            "bitrate": 160,
            "filter": null
        }
    },
    "video": {
        "profile": null,
        "map": 0,
        "field_order": "unknown",
        "codec": "h264",
        "level": null,
        "debug": "base",
        "width": null,
        "bitrate": 955.0749,
        "pix_fmt": null
    },
    "format": "mp4"
}

**Comment by mdhiggins** [comment]
No I understand that I was just proposing a different means of filtering out bad field_order options that's more consistent with how the script filters out bad options in general at the converter level
According to the ffmpeg documentation there's only a few valid inputs, so I just check it against that list and wipe the option

I just committed the change give it a shot
5b536883e561cadba00806bf8b9e6244e350b222

**Comment by allenderj** [comment]
[ffmpeg_error.log](https://github.com/mdhiggins/sickbeard_mp4_automator/files/4184081/ffmpeg_error.log)

**Comment by mdhiggins** [comment]
In the event ffprobe returns something other than unknown (like unk, und, null, etc) this method would catch that as well

**Comment by allenderj** [comment]
Ah I see . 
I will pull and let you know. 
Thanks for the quick turn around on this.

**Comment by allenderj** [comment]
Yep ran a manual scan on  known mad file and it is working now. Thanks again.

**Comment by mdhiggins** [comment]
Great, thanks for the feedback

**Pull request closed without merging**
