### PR TITLE
Added ability to add files to iTunes at end of processing.

### PR DESCRIPTION
**Pull request by jzucker2**
Wanted to be able to automatically add to iTunes without having to use the "Automatically add to iTunes" folder (I store my media on an external drive). This uses an AppleScript to add a reference to the video to iTunes for playback and inclusion in your library (note: this respects the option in your iTunes preferences to copy all items to your iTunes library folder, uncheck if you want a reference added and not have the file copied again).

### CODE REVIEW

**Comment by jzucker2** [comment]
Added checks for operating systems to prevent exceptions.

**Comment by jzucker2** [comment]
You made some big changes that made this PR useless. Planning on reimplementing this as a post processing hook and making the add to itunes be a module, similar to an offline conversation we had a few months back

**Comment by mdhiggins** [comment]
Still been really busy but started reviewing this. If you could do me a huge favor and just go through and replace any instances of using `print` outside of manual.py to using the logger it'd be appreciated. If you don't have time I'll try and get to it but I'm gonna be super busy for the next couple weeks

**Comment by Trixter69** [comment]
I created a quick batch file to do this on Windows machines as applescript is OSX only.
Make sure "Edit>Preferences>Advanced>Copy files to iTunes Media folder when adding to library" is unchecked before implementing this.

Please note: I'm not sure why but it sometimes starts playing the file after adding it. This has only happened to me 4 times in 300+ conversions, and I've yet to find the reason. 

iTunes.bat
[code]
@echo off
::Put the path to your itunes.exe, This MUST be in quotes if there is a space in the path. i.e. "C:\Program Files\iTunes\iTunes.exe"
set itunespath = "Path to itunes" 
set var=%MH_FILES%
set var2=%var:~1,-1%

start %itunespath% %var2%
[/code]

**Pull request closed without merging**
