### PR TITLE
Add option to set max amount of concurrent instances

### PR DESCRIPTION
**Pull request by hazcod**
Add maxproc option to specify max number of scripts running at a given time. Will wait if no spot free.
Saved in .spot1, .spot2 etc..

Fixes https://github.com/mdhiggins/sickbeard_mp4_automator/issues/325

### CODE REVIEW

**Comment by HazCod** [comment]
I (accidently) also included a check if the file is not per your criteria, it uses ffmpeg to switch containers.
Why are you doing this check while ffmpeg can use others easily?

**Comment by HazCod** [comment]
@mdhiggins had time to look at my pull requests yet?

**Comment by mdhiggins** [comment]
I'll try and review everything this weekend

**Comment by Mirabis** [comment]
Any plans to import this anytime soon, or should I fork/customize my local install?

Looking for ways to speed up processing, and -threads etc reached its limit ;(

**Comment by Mirabis** [comment]
Added this locally, and seems to work... but it never removed the .spot file ;o

**Comment by SgtBatten** [comment]
Id love to implement only processing 1 at a time. My htpc is shit, hence the need to convert everything to a direct play capability using this script. It will not cope with multiple conversions.

Is it as straight forward as downloading this commit?

**Comment by badincite** [comment]
Wondering the same thing. Using collisions fork that uses graphics card acceleration. And the geforce series cards only allow 2 instances of it to be run at a time so i need some way to limit it until I get a couple quadro cards.

**Comment by cgram23** [comment]
@mdhiggins....out of curiosity, are there plans to merge this feature?  I'd rather not fork for stability reasons, but limiting processing to 1 at a time would do wonders to streamline.

And thanks for all the hard work!

**Comment by ethanopp** [comment]
@mdhiggins - any chance of this getting merged?

**Comment by Nottt** [comment]
Is there a fork with this we can use? I'm using it with deluge and just had it spin 40 transcodes at once! lol

**Comment by uchagani** [comment]
I was able to get something similar working by using a queue instead.  SAB post process script adds the filepath to a queue and i have a crontab that runs every minute and runs a processing script.  working great so far.

**Pull request closed without merging**
