### PR TITLE
Add support for qBittorrent

### PR DESCRIPTION
**Pull request by uchagani**
This PR adds support for qBittorrent.  I borrowed heavily from the uTorrent script.  There is a new dependency (`pip install python-qbittorrent`) to allow interaction with qBittorrent easier so we don't have to make the requests ourselves.

- Only `pause` is supported for the `Before` action.
- Only `resume` or `delete` is supported for the `After` action.

### CODE REVIEW

**Comment by uchagani** [comment]
@mdhiggins any chance this can get merged?  I've been personally using this and it works great.

**Comment by mdhiggins** [comment]
Merged!

**Comment by mdhiggins** [comment]
Looks like default options were not added to pre existing installations with the pull. Just updated and added that feature please make sure things are still working on your end as well

**Comment by uchagani** [comment]
oops sorry about that.  thanks for the quick fix.

**Pull request merged**
