### PR TITLE
Tagdata send to Subliminal

### PR DESCRIPTION
**Pull request by Petterooe**
So I tried  my first upload to github.
There are one issue you should attend to even without these changes.
In def downloadsubtitles 

    video = subliminal.scan_video(os.path.abspath(inputfile)) 
subliminal raise exception if not find tv episode if  for some reason guessit thinks it is a tvshow. There should be a try,except there  to try again if original name is provided and create a whole new video from original name if there was an exception before.

### CODE REVIEW

**Comment by mdhiggins** [comment]
4ca5f2b41537304eaad07b9347a71a68404d3338

Addressed with this update

**Comment by Petterooe** [comment]
Great work! that must be the way to do it, more values are added to video object. 
Remains to fix the issue with exceptions from subliminal.

    Traceback (most recent call last):
    File "C:\Users\Pao\sickbeard\sickbeard_mp4_automator\resources\mediaprocessor.py", line 1385, in downloadSubtitles
      video = subliminal.scan_video(os.path.abspath(inputfile))
    File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\core.py", line 372, in scan_video
      video = Video.fromguess(path, guessit(path))
    File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\video.py", line 100, in fromguess
      return Episode.fromguess(name, guess)
    File "C:\Users\Pao\AppData\Local\Programs\Python\Python39\lib\site-packages\subliminal\video.py", line 189, in fromguess
      raise ValueError('Insufficient data to process the guess')
For example this text in a name of a movie causes guessit to think it's an episode (1- ac-3 2015-01-02 -0 x1) and raise exception.
To get a video object to refine this must be bypassed.
When have tagdata we can provide subliminal with a guess, when have ('type': 'movie') there will be no exceptions .

    guess = guessit.guessit(os.path.abspath(inputfile),options={'type': 'movie'} if tagdata.mediatype == MediaType.Movie else 
       {'type': 'episode'} if tagdata.mediatype == MediaType.TV else None)
    video = subliminal.Video.fromguess(os.path.abspath(inputfile),guess)
But then from manual.py there maybe not come any tagdata but an original name, so for also cover that there must also be a mishmash of try except you can get the idea from my code.

**Comment by mdhiggins** [comment]
f5f1fa97be60ab5b1385c70a3bbcfc45da65a7dc

**Comment by mdhiggins** [comment]
Think at this point we have similar enough changes that this doesn't need to be merged plus the history with all the random file deletes etc probably shouldn't be merged into master

Is there anything that the current master is missing compared to the remaining proposed changes here? The silent option changes should ideally be a separate request since that's a different feature

**Comment by Petterooe** [comment]
There were something wrong on github with my code showing diff when there were no diff, so not merge.This is only god way for show suggestions.
Last change you did stopped guessit for think a movie is a tvshow so now movies are fixed, they will not raise exception.
But if it is a tvshow the issue persist with a bad filename, if the episode number is not to be found in the filename a exception will be raised, and the code never reach refine.
So look at my last suggestion, only way I can think of is a new name search to get by guessit.

**Comment by Petterooe** [comment]
To avoid value issues can also use hardcoded name to guessit ex. "The.Big.Bang.Theory.S05E18" it will be overwritten in refine anyway, but would not be so pretty code.

**Comment by mdhiggins** [comment]
cf5def85572539e011bcd95b090f3cb784f1a0b8

Try that

**Comment by Petterooe** [comment]
Perfect! I was wrong it was subliminal that checked for episode not guessit. Now subliminal gets all that hen wants.
Now that there is a fail-safe function for subliminal I suggest you lead the second subliminal there to subliminal.Video.fromname(original).
This is from Sonarr.
os.environ['sonarr_episodefile_scenename']= 'Star.Wars.The.Bad.Batch.S01E09.720p.DSNP.WEBRip.DDP5.1.x264-END[rartv]'
os.environ['sonarr_episodefile_path']= 'E:\...\Star.Wars.The.Bad.Batch.S01E09.720p.DSNP.WEBRip.DDP5.1.x264-END[rartv].mkv'
The original and the filepath is the same, so if the first subliminal wants to bail out the second will bail to.
Here is from subliminal :

    @classmethod
    def fromname(cls, name):
        """Shortcut for :meth:`fromguess` with a `guess` guessed from the `name`.
        :param str name: name of the video.
        """
        return cls.fromguess(name, guessit(name))

**Comment by mdhiggins** [comment]
I don't follow what you're trying to say

I'm thinking maybe you mean the `original` code should be modified

```
                if original:
                    self.log.debug("Found original filename, adding data from %s." % original)
                    og = subliminal.Video.fromname(original)
                    self.log.debug("Source %s, release group %s, resolution %s." % (og.source, og.release_group, og.resolution))
                    video.source = og.source or video.source
                    video.release_group = og.release_group or video.release_group
                    video.resolution = og.resolution or video.resolution
```

Is that what you're referencing?

That only really exists to capture source / release_group / resolution information so if really don't matter if it guesses the wrong type

**Comment by Petterooe** [comment]
Yes I mean that subliminal. It's the same there if he guess tvshow but not find episode number a valueerror will rise and then downloadsubs will be exited. But it's also enough to put try except there for not exit download, an error there will not destroy the original video object.
It's not easy to know when guessit set it as episode when I test it is always different as if whole filename matters or something before he set ac-3 as episode but not the last time I tested. Best is to protect from this guess.It is as you said before guessit is not a reliant solution it is only a guess.

**Comment by Petterooe** [comment]
Here is the method in subliminal that raise the valueerror for not have an episode number. 
 
    @classmethod
     def fromguess(cls, name, guess):
        if guess['type'] != 'episode':
            raise ValueError('The guess must be an episode guess')

        if 'title' not in guess or 'episode' not in guess:
            raise ValueError('Insufficient data to process the guess')

**Comment by mdhiggins** [comment]
b3056f871a36bc07deba5c1f45bb9ec873b0220f

Rather than creating another subliminal object and copying the parameters we can avoid this whole scenario and just use guessit to get the parameters and pass them on

**Comment by Petterooe** [comment]
Oh! my my. That was such a clever  way of solving it. Guessit not throw exceptions.
Now I don't have any more suggestions, you can close this now. 

Should be an improvement now when the correct title and not any extra text is searched for, and the correct year is crucial.

I really appreciate your script it gives the possibility to add whatever feature there is need for, not bound as you would be with a program. Many thanks for this.

Looked at sonarr and radarr but I don't think the asian indexers I use is to be found there. It's media with both thai dubb and english sound that is preferred. Have you heard of any of the registered indexers or usenet could have such content ?

**Comment by mdhiggins** [comment]
Included

**Pull request closed without merging**
