### PR TITLE
Merge with upstream (stable) guessit

### PR DESCRIPTION
**Pull request by outlyer**
Upstream wackou/guessit@e5d667a2b00adc4730436b0f93ef7ee273c3fd0a is at 0.10.2 and has many improvements in the heuristics
used to guess filenames. The only major change for this project is that the
```guess_video_info()``` function has been renamed to ```guess_file_info()```

### CODE REVIEW

**Comment by mdhiggins** [comment]
Thanks!

**Comment by mdhiggins** [comment]
This appears to break things if you don't also update babelfish. Just pushed the latest babelfish as well. 

4cf8dd132451e313429a8b6f8a5a6e0f4c5e525f

**Comment by mdhiggins** [comment]
Looks like this merge also reverted a lot of manual.py changes back to a much older version (before all the logging was implemented) and users were getting an error. I just pushed a commit that reverts that minus the `guess_video_info` to `guess_file_info` change.

**Comment by outlyer** [comment]
@mdhiggins Sorry about the mess; I am positive I did a manual pull from the origin/master repo before making the fork so I can't figure out how this happened. But, again, sorry about the annoyances.

**Comment by mdhiggins** [comment]
No worries, just wanted to tell you so you could fix your setup

**Pull request merged**
