### PR TITLE
Fix original path deletion in Deluge Post Process

### PR DESCRIPTION
**Pull request by davidbgeek**
I've fixed the delugePostProcess.py to now include original path deletion which it didn't seem to have before for some reason. Also made the temporary folder deletion first delete all files within dir, then dir itself since it was causing an issue on Windows.

### CODE REVIEW

**Comment by justinglock40** [comment]
Will this address this error?

2017-05-04 01:19:09 - mkvtomp4 - INFO - G:\Complete\Catfish.The.TV.Show.S06E10.720p.HDTV.x264-W4F[rarbg]-convert\catfish.the.tv.show.s06e10.720p.hdtv.x264-w4f.mp4 created.
2017-05-04 01:19:09 - delugePostProcess - INFO - Passing G:\Complete\Catfish.The.TV.Show.S06E10.720p.HDTV.x264-W4F[rarbg]-convert directory to Sonarr.
2017-05-04 01:19:09 - autoprocess.sonarr - INFO - Sonarr notifier started.
2017-05-04 01:19:09 - autoprocess.sonarr - INFO - Requesting Sonarr to scan directory 'G:\Complete\Catfish.The.TV.Show.S06E10.720p.HDTV.x264-W4F[rarbg]-convert'.
2017-05-04 01:19:09 - autoprocess.sonarr - INFO - Sonarr response: queued.
2017-05-04 01:19:09 - delugePostProcess - ERROR - Unable to delete temporary directory.
Traceback (most recent call last):
  File "C:\Sickbeard\delugePostProcess.py", line 121, in <module>
    os.rmdir(delete_dir)
WindowsError: [Error 145] The directory is not empty: 'G:\\Complete\\Catfish.The.TV.Show.S06E10.720p.HDTV.x264-W4F[rarbg]-convert'

**Comment by davidbgeek** [comment]
It might. I'm still not completely sure what causes it to fail sometimes. You can try replacing your code with mine and see what happens.

**Comment by mdhiggins** [comment]
So this probably won't work reliably because any files that are being actively seeded are gonna be flagged as in use and the delete will fail.

The better and probably more proper way to handle this would be using the deluge API to trigger a `remove_torrent` action with `remove_data` set to `true`

**Comment by mdhiggins** [comment]
Just pushed a new commit that adds that above functionality - give it a try
This will also prevent corrupted/orphaned torrents from remaining in your deluge client with their data deleted

**Comment by davidbgeek** [comment]
It now succeeds in deleting the `*-convert` directory, but the original one still remains.

**Comment by justinglock40** [comment]
mdhiggins Is there anyway to have the script wait for unraring and ignore samples before converting?

**Pull request closed without merging**
